name: Sync to GitLab

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history

      - name: Add GitLab remote and push
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.reutlingen-university.de/lauterba/boom-chess.git
          git checkout -b gitlab-master
          git push gitlab HEAD:master --force




