name: Sync to GitLab

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "martin.lauterbach@student.reutlingen-university.de"
          git config --global user.name "Marty"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.reutlingen-university.de/lauterba/boom-chess.git
        run: |
          git remote add gitlab $GITLAB_REPO
          git push gitlab HEAD:master


