name: Sync to GitLab

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: https://oauth2:${{ secrets.GITLAB_TOKEN }}@https://gitlab.reutlingen-university.de/lauterba/boom-chess
        run: |
          git remote add gitlab $https://gitlab.reutlingen-university.de/lauterba/boom-chess
          git push gitlab HEAD:main

